# version: "3.9"

# services:
#   backend:
#     container_name: backend
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.backend
#     environment:
#       - PORT=6000
#     ports:
#       - "6000:6000"
#     networks:
#       - app-network
#     restart: always

#   nginx:
#     container_name: nginx
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.frontend
#     depends_on:
#       - backend
#     ports:
#       - "80:80"
#     networks:
#       - app-network
#     restart: always

  
# networks:
#   app-network:
#     driver: bridge
version: "3.9"

services:
  portal_mysql:
    image: mysql:8
    container_name: portal_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fullstack_test_portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: fullstack123@
    ports:
      - "3307:3306"
    volumes:
      - portal_mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      PORT: 6000
      DB_HOST: portal_mysql
      DB_PORT: 3306
      DB_USER: portal_user
      DB_PASSWORD: fullstack123@
      DB_NAME: fullstack_test_portal
    ports:
      - "6000:6000"
    depends_on:
      - portal_mysql
    networks:
      - app-network
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "100:100"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  portal_mysql_data:
